DROP DATABASE IF exists db5;
CREATE DATABASE IF NOT EXISTS db5 CHARACTER SET UTF8;
	/*CHARACTER SET cp1251*/;

USE db5;

CREATE TABLE IF NOT EXISTS PARTICIPANTS (
	PARTICIPANT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PART_NAME VARCHAR(30) NOT NULL,
	PART_SURNAME VARCHAR(30) NOT NULL,
	ADDRESS VARCHAR(50) NOT NULL
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS PERMISSIONS (
	PERMISSION_ID MEDIUMINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ROLE VARCHAR(50) NOT NULL UNIQUE
) ENGINE INNODB;

CREATE TABLE IF NOT EXISTS GROUPS (
	GROUP_ID MEDIUMINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	GROUP_NAME VARCHAR(50) NOT NULL UNIQUE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS GROUP_PERMISSION (
	GROUP_ID MEDIUMINT NOT NULL,
	PERMISSION_ID MEDIUMINT NOT NULL,
	PRIMARY KEY(GROUP_ID, PERMISSION_ID),
	FOREIGN KEY(GROUP_ID)
		REFERENCES GROUPS(GROUP_ID)
		ON DELETE CASCADE,
	FOREIGN KEY(PERMISSION_ID)
		REFERENCES PERMISSIONS(PERMISSION_ID)
		ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS USER_INFO (
	USER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	PARTICIPANT_ID INT NOT NULL,
	LOGIN VARCHAR(30) NOT NULL UNIQUE,
	USER_PASSWORD VARCHAR(60) NOT NULL,
	ACCOUNT_NOT_EXPIRED BOOL NOT NULL,
	ACCOUNT_NOT_BLOCKED BOOL NOT NULL,
	CREDENTIALS_NOT_EXPIRED BOOL NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	FOREIGN KEY(PARTICIPANT_ID)
		REFERENCES PARTICIPANTS(PARTICIPANT_ID)
		ON DELETE CASCADE
) ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS USER_GROUP (
	USER_ID INT NOT NULL,
	GROUP_ID MEDIUMINT NOT NULL,
	PRIMARY KEY(USER_ID, GROUP_ID),
	FOREIGN KEY(USER_ID)
		REFERENCES USER_INFO(USER_ID)
		ON DELETE CASCADE,
	FOREIGN KEY(GROUP_ID)
		REFERENCES GROUPS(GROUP_ID)
		ON DELETE CASCADE
) ENGINE=INNODB;