use db5;

CREATE TABLE IF NOT EXISTS STUDENT (
	STUDENT_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR(45) NOT NULL,
	ADDRESS VARCHAR(45) NOT NULL,
	PHONE VARCHAR(45) NOT NULL
) ENGINE=INNODB;